export const appState = {
  user: {
    firstName: "Frank",
    timeZone: "America/New_York",
    preferredWakeTime: "07:00",
    preferredBedTime: "22:30",
    reminderStyle: "Clear, specific, low-friction prompts",
  },
  selectedSnapshot: {
    Home: ["Own Home"],
    Work: ["Business Owner"],
    Transportation: ["Motorcycle", "Car"],
    Health: ["Medications to Track", "Medical Appointments to Track"],
    Family: ["Pets"],
    Finances: ["Bills", "Insurance"],
    Projects: ["Personal Projects", "Business Projects"],
  },
  interview: {
    currentQuestionId: "adhd-primary",
    completed: false,
  },
  ui: {
    activeView: "working",
    lastMorningBriefingDate: null,
  },
  interviewProfile: {
    adhd: {},
    fitness: {},
    health: {},
    work: {},
    money: {},
    relationships: {},
    activeRulesets: [
      "one_next_action",
      "decision_fatigue_reduction",
      "memory_backup",
      "progressive_profile",
      "gentle_escalation",
    ],
  },
  responsibilityAreas: [
    {
      id: "health",
      name: "Health",
      status: "Needs attention",
      lastReviewedAt: "Today",
      summary: "Morning medication is waiting and an appointment is coming up next week.",
      actions: ["Take morning medication", "Confirm doctor appointment time"],
    },
    {
      id: "home",
      name: "Home",
      status: "Stable",
      lastReviewedAt: "3 days ago",
      summary: "Home profile exists; insurance and property tax details can be filled in later.",
      actions: ["Add home insurance details"],
    },
    {
      id: "business",
      name: "Business",
      status: "Active",
      lastReviewedAt: "Yesterday",
      summary: "Client follow-up and domain renewal are visible.",
      actions: ["Reply to client", "Review domain renewal date"],
    },
    {
      id: "transportation",
      name: "Transportation",
      status: "Monitor",
      lastReviewedAt: "4 days ago",
      summary: "Motorcycle tire check should stay on the radar.",
      actions: ["Check rear tire condition"],
    },
    {
      id: "pets",
      name: "Pets",
      status: "Profile needed",
      lastReviewedAt: "Not started",
      summary: "Pet care can become its own profile once the basic snapshot is confirmed.",
      actions: ["Create pet profile"],
    },
    {
      id: "finances",
      name: "Finances",
      status: "Due soon",
      lastReviewedAt: "Today",
      summary: "Electric bill needs payment and insurance renewal is approaching.",
      actions: ["Pay electric bill", "Check insurance renewal amount"],
    },
    {
      id: "projects",
      name: "Projects",
      status: "Protected time",
      lastReviewedAt: "Today",
      summary: "Dragon fairing project has a focused work block today.",
      actions: ["Work on motorcycle fairing"],
    },
  ],
  profiles: [
    { id: "home-profile", areaId: "home", name: "Home Profile", details: ["Insurance", "Property taxes", "Mortgage"] },
    { id: "motorcycle-profile", areaId: "transportation", name: "Motorcycle Profile", details: ["Year", "Make", "Model", "Mileage"] },
    { id: "business-profile", areaId: "business", name: "Business Profile", details: ["LLC", "Domains", "Hosting", "Software subscriptions"] },
    { id: "health-profile", areaId: "health", name: "Health Profile", details: ["Medications", "Providers", "Conditions"] },
    { id: "pet-profile", areaId: "pets", name: "Pet Profile", details: ["Vet", "Medications", "Food"] },
  ],
  routines: [
    { id: "routine-med-am", name: "Morning medications", time: "7:30 AM", areaId: "health", completed: false, priority: "High", estimatedEffortMinutes: 5 },
    { id: "routine-breakfast", name: "Breakfast", time: "8:00 AM", areaId: "health", completed: true, priority: "Medium", estimatedEffortMinutes: 20 },
    { id: "routine-exercise", name: "Exercise", time: "5:30 PM", areaId: "health", completed: false, priority: "Medium", estimatedEffortMinutes: 30 },
    { id: "routine-med-pm", name: "Evening medications", time: "9:00 PM", areaId: "health", completed: false, priority: "High", estimatedEffortMinutes: 5 },
    { id: "routine-bed", name: "Bedtime routine", time: "10:00 PM", areaId: "health", completed: false, priority: "Medium", estimatedEffortMinutes: 20 },
  ],
  actions: [
    { id: "action-insurance", areaId: "finances", title: "Call insurance company", timingType: "flexible", preferredWindow: "Today", dueDate: "Today", status: "todo", priority: "High", estimatedEffortMinutes: 15 },
    { id: "action-electric", areaId: "finances", title: "Pay electric bill", timingType: "deadline", deadline: "Today", dueDate: "Today", status: "todo", priority: "High", estimatedEffortMinutes: 10 },
    { id: "action-doctor", areaId: "health", title: "Confirm doctor appointment", timingType: "deadline", deadline: "Tomorrow", dueDate: "Tomorrow", status: "todo", priority: "Medium", estimatedEffortMinutes: 10 },
    { id: "action-client", areaId: "business", title: "Reply to client", timingType: "flexible", preferredWindow: "Today", dueDate: "Today", status: "waiting", priority: "Medium", estimatedEffortMinutes: 25, workType: "revenue" },
  ],
  obligations: [
    { id: "ob-home-insurance", profileId: "home-profile", name: "Home insurance", dueDate: "In 43 days", status: "Needs review", urgency: "Soon" },
    { id: "ob-registration", profileId: "motorcycle-profile", name: "Motorcycle registration", dueDate: "Next month", status: "Upcoming", urgency: "Soon" },
    { id: "ob-med-refill", profileId: "health-profile", name: "Medication refill", dueDate: "In 9 days", status: "Check supply", urgency: "Soon" },
  ],
  discoveries: [
    { id: "discovery-placeholder", areaId: "transportation", title: "Manual note: rear tire may require replacement", source: "Prototype seed", status: "Review" },
  ],
  recommendationState: {},
  guidanceState: {},
  morningRoutineState: {},
  learningStats: {},
  recoveryState: {},
  recoveryHistory: [],
  tipState: {
    recentTipIds: [],
    lastShownByContext: {},
  },
  focusMode: null,
  focusHistory: [],
  progressHistory: [],
  endOfDayReviews: {},
  weeklyReviewHistory: {},
  waitingOn: [
    { id: "wait-insurance", title: "Insurance quote", owner: "Insurance company", areaId: "finances" },
    { id: "wait-doctor", title: "Doctor office callback", owner: "Provider office", areaId: "health" },
  ],
  focusSessions: [
    {
      id: "focus-motorcycle",
      name: "Work on motorcycle fairing",
      startTime: "9:00 AM",
      plannedEndTime: "10:30 AM",
      transitionWarningTime: "10:20 AM",
      nextTask: "Pay electric bill",
      priority: "Medium",
      flexibility: "Can move by 30 minutes",
      areaId: "projects",
      timingType: "scheduled",
      startTime: "9:00 AM",
      estimatedEffortMinutes: 90,
    },
    {
      id: "focus-bills",
      name: "Pay bills",
      startTime: "10:45 AM",
      plannedEndTime: "11:15 AM",
      transitionWarningTime: "11:05 AM",
      nextTask: "Lunch",
      priority: "High",
      flexibility: "Do today",
      areaId: "finances",
      timingType: "scheduled",
      startTime: "10:45 AM",
      estimatedEffortMinutes: 30,
    },
  ],
  timeline: [
    { id: "tl-breakfast", time: "8:00 AM", title: "Breakfast", type: "Routine", areaId: "health", status: "Done", priority: "Medium", timingType: "scheduled", startTime: "8:00 AM", estimatedEffortMinutes: 20 },
    { id: "tl-focus-start", time: "9:00 AM", title: "Start: Work on motorcycle fairing", type: "Focus Session", areaId: "projects", status: "Upcoming", priority: "Medium", timingType: "scheduled", startTime: "9:00 AM", estimatedEffortMinutes: 90 },
    { id: "tl-focus-warning", time: "10:20 AM", title: "Wrap up motorcycle work", type: "Transition Reminder", areaId: "projects", status: "Upcoming", priority: "Medium", timingType: "scheduled", startTime: "10:20 AM", estimatedEffortMinutes: 10 },
    { id: "tl-focus-stop", time: "10:30 AM", title: "Stop motorcycle work. Next: Pay electric bill", type: "Transition Reminder", areaId: "finances", status: "Upcoming", priority: "High", timingType: "scheduled", startTime: "10:30 AM", estimatedEffortMinutes: 5 },
    { id: "tl-bills", time: "10:45 AM", title: "Pay electric bill", type: "Action", areaId: "finances", status: "Upcoming", priority: "High", timingType: "scheduled", startTime: "10:45 AM", estimatedEffortMinutes: 10 },
    { id: "tl-exercise", time: "5:30 PM", title: "Exercise", type: "Routine", areaId: "health", status: "Upcoming", priority: "Medium", timingType: "scheduled", startTime: "5:30 PM", estimatedEffortMinutes: 30 },
    { id: "tl-bedtime", time: "10:00 PM", title: "Begin bedtime routine", type: "Transition Reminder", areaId: "health", status: "Upcoming", priority: "Medium", timingType: "scheduled", startTime: "10:00 PM", estimatedEffortMinutes: 20 },
  ],
};
