export const appState = {
  user: {
    firstName: "",
    timeZone: "America/New_York",
    preferredWakeTime: "07:00",
    preferredBedTime: "22:30",
    reminderStyle: "Clear, specific, low-friction prompts",
  },
  selectedSnapshot: {
    Home: [],
    Work: [],
    Transportation: [],
    Health: [],
    Family: [],
    Finances: [],
    Projects: [],
  },
  interview: {
    currentQuestionId: "adhd-primary",
    completed: false,
  },
  ui: {
    activeView: "setup",
    lastMorningBriefingDate: null,
    setup: {
      progressive: {
        step: "intro",
        introSeen: false,
        name: "",
        helpArea: "",
        firstThing: "",
        moreThings: "",
        completed: false,
        starterItem: null,
      },
      skippedSteps: [],
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#dfeeff",
      overlay: "medium",
      imageDataUrl: "",
      imageName: "",
    },
    account: {
      displayName: "",
      profilePhotoDataUrl: "",
      profilePhotoName: "",
      privacyLock: {
        enabled: false,
        passcodeHash: "",
        lastChangedAt: null,
      },
    },
  },
  interviewProfile: {
    adhd: {},
    fitness: {},
    health: {},
    work: {},
    money: {},
    relationships: {},
    activeRulesets: [
      "one_next_action",
      "decision_fatigue_reduction",
      "memory_backup",
      "progressive_profile",
      "gentle_escalation",
    ],
  },
  responsibilityAreas: [
    {
      id: "health",
      name: "Health",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add health routines, medications, movement, meals, or appointments when you are ready.",
      actions: [],
    },
    {
      id: "home",
      name: "Home",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add home responsibilities when you want the assistant to help keep them visible.",
      actions: [],
    },
    {
      id: "business",
      name: "Business",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add work responsibilities, follow-ups, projects, or revenue tasks when useful.",
      actions: [],
    },
    {
      id: "transportation",
      name: "Transportation",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add vehicle, travel, or transportation needs if they matter to your day.",
      actions: [],
    },
    {
      id: "pets",
      name: "Pets",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add pet care routines or reminders later if they are part of your life.",
      actions: [],
    },
    {
      id: "finances",
      name: "Finances",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add bills, renewals, savings goals, or money tasks when you want support.",
      actions: [],
    },
    {
      id: "projects",
      name: "Projects",
      status: "Ready to teach",
      lastReviewedAt: "Not started",
      summary: "Add personal projects, hobbies, repairs, or dreams you want help moving forward.",
      actions: [],
    },
  ],
  profiles: [],
  routines: [],
  actions: [],
  obligations: [],
  discoveries: [],
  recommendationState: {},
  guidanceState: {},
  morningRoutineState: {},
  learningStats: {},
  recoveryState: {},
  recoveryHistory: [],
  tipState: {
    recentTipIds: [],
    lastShownByContext: {},
  },
  positiveReinforcementState: {
    recentMessageIds: [],
    currentByContext: {},
  },
  voiceListEntry: {
    drafts: {},
    savedLists: {
      foodMeals: [],
      shoppingList: [],
      routineSteps: [],
    },
  },
  interventionState: {
    recentInterventionIds: [],
    lastShownByContext: {},
    dismissedToday: [],
    effectiveness: {},
    history: [],
  },
  energyMood: {
    checkIns: [],
  },
  smartReschedulingState: {
    history: [],
    lastRunDate: null,
  },
  routinePlans: [],
  routineStepState: {},
  routineBuilderDraftId: null,
  goals: [],
  goalDraftId: null,
  projects: [],
  projectDraftId: null,
  meals: [],
  notes: [],
  habits: [],
  habitDraftId: null,
  habitCompletions: {},
  recurringTasks: [],
  recurringTaskDraftId: null,
  recurringTaskCompletions: {},
  recurringOccurrenceState: {},
  focusMode: null,
  focusHistory: [],
  progressHistory: [],
  endOfDayReviews: {},
  weeklyReviewHistory: {},
  waitingOn: [],
  focusSessions: [],
  timeline: [],
};
